files:
  - source: /locales/ja-JP.yml
    translation: /locales/%locale%.yml
    update_option: update_as_unapproved
  - source: /content/ja/docs/**/*.*
    translation: /content/%two_letters_code%/docs/**/%original_file_name%.%file_extension%
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        zh-TW: tw
        zh-CN: cn
