files:
	- source: /locales/ja-JP.yml
		translation: /locales/%locale%.yml
		update_option: update_as_unapproved
	- source: /content/ja-JP/docs/**/*.*
		translation: /content/%locale%/docs/**/%original_file_name%
		update_option: update_as_unapproved
	